### ISSUE TITLE
Activate.sh seems to cause -bash: fork: Resource temporarily unavailable

### ISSUE THREAD

**Issue by Mayestril** [kennethreitz/autoenv#155]
As soon as I have run `echo "source $(brew --prefix autoenv)/activate.sh" >> ~/.bash_profile` and restart the terminal I get multiple `-bash: fork: Resource temporarily unavailable` messages. 
As soon as I line-comment `source /usr/local/opt/autoenv/activate.sh` my terminal returns to normal.

Any suggestions on what to do or how to properly debug?

**Comment by ernstki** [comment]
Did this behavior persist after a reboot? (I'm assuming this is a personal computer, since you're using Homebrew.) When `fork` fails, for me it's always a sign that the OS is unhappy, like I accidentally wrote a script that's spawning thousands of processes until some kind of process limit is reached.

If it _did_ persist after a reboot, do you see the same behavior when you create a "dummy" user in OS X and install autoenv _just_ for that user, by either `git clone`ing a fresh copy of the repository while logged in as that user or downloading and extracting a .zip of the [latest release](../releases) from GitHub, then sourcing `/path/to/activate.sh` within `~/.bashrc`?

**Comment by dasJ** [comment]
Sounds like a forkbomb to me, maybe the autoenv loop never breaks. Can you `set -x` and send me the output?

**Comment by dasJ** [comment]
Closing for now
