### ISSUE TITLE
disable for subfolders

### ISSUE THREAD

**Issue by aljosa** [kennethreitz/autoenv#37]
$ cd autoenv_folder # works, activates .env
$ cd autoenv_subfolder # works, activates .env from parent folder

any way to force sourcing of .env only when in folder and not subfolders?

**Comment by thiswillbeyourgithub** [comment]
I did this and it seems to work fine:

edit ~/.autoenv/activate.sh to add those 5 lines:

```sh

# @description Main initialization function
# @internal
autoenv_init() {
	if [ -n "$AUTOENV_ENABLE_LEAVE" ]; then
		autoenv_leave "$@"
	fi

  # DIY: don't execute in subfolders
  if [ ! -f .env ]
  then
    builtin cd "$(pwd -P)"
    return
  fi

...rest of the code...
```

This blocks the .env but not the .env.leave, this way I only run the initialization scripts once (and not in each subfolder) but also have the deinitialization script run no matter from which subfolder I get out.

It would be nice if this could be an official setting. My use cases are varied, for example there is a repository where when I cd into it, it curls an online openapi.json spec file and prints me the diff with the currently implemented one so that I know if I my client api code is outdated. I also have scripts that automatically sync my readme.md roadmaps with Logseq.
